Repository OurTimeForTech/shiftwork2, pull requests merged in 2021-04, with the labels that each got.

#20 Prevent logged in users from accessing /login
  app/controllers/sessions_controller.rb
Labels: Merged

#22 Build Out Organizations Edit UI
  app/controllers/organizations_controller.rb
  app/views/organizations/edit.html.erb
Labels: Ready for Merge

#23 UI for General&Shared views step 4: change form error messages
  config/application.rb
Labels: Ready for Merge

#25 Sign up view for User UI
  app/views/users/new.html.erb
Labels: Ready for Merge

#26 Edit view for User UI
  app/views/users/edit.html.erb
Labels: Ready for Merge

#27 New Organizations View UI
  app/views/organizations/new.html.erb
Labels: Ready for Merge

#28 Add authorization to Organization Show UI
  app/controllers/organizations_controller.rb
  app/views/organizations/show.html.erb
Labels: Ready for Merge

#29 Organisations can only see their shifts and can see the edit/create/delete shift buttons
  app/controllers/shifts_controller.rb
  app/views/shifts/index.html.erb
Labels: Ready for Merge

#36 Updated unauthorized message
  app/controllers/organizations_controller.rb
Labels: Ready For QA

#34 New View for WorkersUI
  app/controllers/workers_controller.rb
  app/views/workers/new.html.erb
Labels: Ready For QA

#31 Show View for User UI
  app/views/users/show.html.erb
Labels: Ready For QA

#32 Edit Workers UI View
  app/controllers/workers_controller.rb
  app/views/workers/edit.html.erb
Labels: Ready For QA

#33 Styling shifts view
  Gemfile.lock
  app/assets/stylesheets/shifts.scss
  app/views/shifts/index.html.erb
Labels: Ready For QA

#43 Sara add drop shift button to shifts view
  app/views/shifts/index.html.erb
Labels: Merged

#42 styling shifts edit view
  app/views/shifts/edit.html.erb
Labels: Merged

#40 styling new shift view
  app/views/shifts/new.html.erb
Labels: Merged

#39 Small update to improve the grid shifts view
  app/views/shifts/index.html.erb
Labels: Merged

#38 Show Org view
  app/controllers/organizations_controller.rb
  app/views/organizations/show.html.erb
Labels: Merged

#37 Update New Org UI
  app/views/organizations/new.html.erb
Labels: Merged

#51 Polished the show views including when org or worker is not created
  app/views/users/show.html.erb
Labels: Ready For QA

#49 prevent workers to access the new shift page
  app/controllers/shifts_controller.rb
Labels: In Progress

#54 Prevent logged in users from accessing sign up page
  app/controllers/users_controller.rb
Labels: Ready For QA

#50 Prevent orgs to see other orgs by id
  app/controllers/organizations_controller.rb
Labels: In Progress

#48 create shift_owner method to prevent other users to edit shifts
  app/controllers/shifts_controller.rb
Labels: In Progress

#58 Sara refactoring permissions in organisations
  app/controllers/organizations_controller.rb
  app/views/organizations/show.html.erb
Labels: Ready For QA

#59 Sara refactoring permissions in shifts
  app/controllers/shifts_controller.rb
Labels: Ready For QA

#60 Put workers permissions in place
  app/controllers/workers_controller.rb
Labels: Ready For QA

#61 home page ui
  app/controllers/users_controller.rb
  app/views/users/index.html.erb
Labels: Ready For QA

#62 Timi Style Workers Show-view
  app/views/workers/show.html.erb
Labels: Ready For QA

#64 Add bio to workers table
  db/migrate/20210428203135_add_bio_to_workers.rb
  db/schema.rb
Labels: Ready For QA

#67 Set conditional org view
  app/controllers/organizations_controller.rb
  app/views/organizations/show.html.erb
Labels: Ready For QA

#71 add verify-access to users controller
  app/controllers/users_controller.rb
Labels: Ready For QA

#72 change flash alert on verify access to warning to have a yellow bkg
  app/controllers/organizations_controller.rb
  app/controllers/shifts_controller.rb
  app/controllers/workers_controller.rb
Labels: Ready For QA
